#!/bin/bash

source "$(dirname "$0")/scripts/library.sh"

clear
echo "     _       _    __ _ _            "
echo "  __| | ___ | |_ / _(_) | ___  ___  "
echo " / _' |/ _ \| __| |_| | |/ _ \/ __| "
echo "| (_| | (_) | |_|  _| | |  __/\__ \ "
echo " \__,_|\___/ \__|_| |_|_|\___||___/ "
echo "                                    "
echo "-------------------------------------"
echo ""

if [ -d ~/.config ]; then
  echo ".config folder already exists."
else
  mkdir ~/.config
  echo ".config folder created."
fi

# ------------------------------------------------------
# Create symbolic links
# ------------------------------------------------------

# create dirs
mkdir -p "$HOME/.ssh"


# linking
create_symlink "$HOME/dotfiles/zsh/.zshrc" "$HOME/.zshrc"
create_symlink "$HOME/dotfiles/git" "$HOME/.config/git"
create_symlink "$HOME/dotfiles/.tool-versions" "$HOME/.tool-versions"
create_symlink "$HOME/dotfiles/aurorae" "$HOME/.local/share/aurorae"
create_symlink "$HOME/dotfiles/colorschemes" "$HOME/.local/share/colorschemes"
create_symlink "$HOME/dotfiles/icons" "$HOME/.local/share/icons"
create_symlink "$HOME/dotfiles/knewstuff3/colorschemes.knsregistry" "$HOME/.local/share/knewstuff3/colorschemes.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/gtk_themes.knsregistry" "$HOME/.local/share/knewstuff3/gtk_themes.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/icons.knsregistry" "$HOME/.local/share/knewstuff3/icons.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/kwinscripts.knsregistry" "$HOME/.local/share/knewstuff3/kwinscripts.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/lookandfeel.knsregistry" "$HOME/.local/share/knewstuff3/lookandfeel.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/plasma-themes.knsregistry" "$HOME/.local/share/knewstuff3/plasma-themes.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/plasmoids.knsregistry" "$HOME/.local/share/knewstuff3/plasmoids.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/sddmtheme.knsregistry" "$HOME/.local/share/knewstuff3/sddmtheme.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/wallpaper.knsregistry" "$HOME/.local/share/knewstuff3/wallpaper.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/window-decorations.knsregistry" "$HOME/.local/share/knewstuff3/window-decorations.knsregistry"
create_symlink "$HOME/dotfiles/knewstuff3/xcursor.knsregistry" "$HOME/.local/share/knewstuff3/xcursor.knsregistry"
create_symlink "$HOME/dotfiles/konsole" "$HOME/.local/share/konsole"
create_symlink "$HOME/dotfiles/kwin" "$HOME/.local/share/kwin"
create_symlink "$HOME/dotfiles/plasma" "$HOME/.local/share/plasma"
create_symlink "$HOME/dotfiles/dolphin" "$HOME/.local/share/dolphin"
create_symlink "$HOME/dotfiles/.themes" "$HOME/.themes"
create_symlink "$HOME/dotfiles/.icons" "$HOME/.icons"
create_symlink "$HOME/dotfiles/arkrc" "$HOME/.config/arkrc"
create_symlink "$HOME/dotfiles/auroraerc" "$HOME/.config/auroraerc"
create_symlink "$HOME/dotfiles/baloofilerc" "$HOME/.config/baloofilerc"
create_symlink "$HOME/dotfiles/bluedevilglobalrc" "$HOME/.config/bluedevilglobalrc"
create_symlink "$HOME/dotfiles/breezerc" "$HOME/.config/breezerc"
create_symlink "$HOME/dotfiles/discoverrc" "$HOME/.config/discoverrc"
create_symlink "$HOME/dotfiles/dolphinrc" "$HOME/.config/dolphinrc"
create_symlink "$HOME/dotfiles/drkonqirc" "$HOME/.config/drkonqirc"
create_symlink "$HOME/dotfiles/gtk-3.0" "$HOME/.config/gtk-3.0"
create_symlink "$HOME/dotfiles/gtk-4.0" "$HOME/.config/gtk-4.0"
create_symlink "$HOME/dotfiles/gtkrc" "$HOME/.config/gtkrc"
create_symlink "$HOME/dotfiles/gtkrc-2.0" "$HOME/.config/gtkrc-2.0"
create_symlink "$HOME/dotfiles/kactivitymanagerdrc" "$HOME/.config/kactivitymanagerdrc"
create_symlink "$HOME/dotfiles/kactivitymanagerd-statsrc" "$HOME/.config/kactivitymanagerd-statsrc"
create_symlink "$HOME/dotfiles/kconf_updaterc" "$HOME/.config/kconf_updaterc"
create_symlink "$HOME/dotfiles/KDE" "$HOME/.config/KDE"
create_symlink "$HOME/dotfiles/kded5rc" "$HOME/.config/kded5rc"
create_symlink "$HOME/dotfiles/kded6rc" "$HOME/.config/kded6rc"
create_symlink "$HOME/dotfiles/kdedefaults" "$HOME/.config/kdedefaults"
create_symlink "$HOME/dotfiles/kdeglobals" "$HOME/.config/kdeglobals"
create_symlink "$HOME/dotfiles/kde.org" "$HOME/.config/kde.org"
create_symlink "$HOME/dotfiles/kglobalshortcutsrc" "$HOME/.config/kglobalshortcutsrc"
create_symlink "$HOME/dotfiles/kiorc" "$HOME/.config/kiorc"
create_symlink "$HOME/dotfiles/konsolerc" "$HOME/.config/konsolerc"
create_symlink "$HOME/dotfiles/konsolesshconfig" "$HOME/.config/konsolesshconfig"
create_symlink "$HOME/dotfiles/ksmserverrc" "$HOME/.config/ksmserverrc"
create_symlink "$HOME/dotfiles/ktimezonedrc" "$HOME/.config/ktimezonedrc"
create_symlink "$HOME/dotfiles/kwalletrc" "$HOME/.config/kwalletrc"
create_symlink "$HOME/dotfiles/kwinoutputconfig.json" "$HOME/.config/kwinoutputconfig.json"
create_symlink "$HOME/dotfiles/kwinrc" "$HOME/.config/kwinrc"
create_symlink "$HOME/dotfiles/PlasmaDiscoverUpdates" "$HOME/.config/PlasmaDiscoverUpdates"
create_symlink "$HOME/dotfiles/plasma-localerc" "$HOME/.config/plasma-localerc"
create_symlink "$HOME/dotfiles/plasmanotifyrc" "$HOME/.config/plasmanotifyrc"
create_symlink "$HOME/dotfiles/plasma-org.kde.plasma.desktop-appletsrc" "$HOME/.config/plasma-org.kde.plasma.desktop-appletsrc"
create_symlink "$HOME/dotfiles/plasmarc" "$HOME/.config/plasmarc"
create_symlink "$HOME/dotfiles/plasmashellrc" "$HOME/.config/plasmashellrc"
create_symlink "$HOME/dotfiles/plasma-welcomerc" "$HOME/.config/plasma-welcomerc"
create_symlink "$HOME/dotfiles/powerdevilrc" "$HOME/.config/powerdevilrc"
create_symlink "$HOME/dotfiles/powermanagementprofilesrc" "$HOME/.config/powermanagementprofilesrc"
create_symlink "$HOME/dotfiles/QtProject.conf" "$HOME/.config/QtProject.conf"
create_symlink "$HOME/dotfiles/sddmthemeinstallerrc" "$HOME/.config/sddmthemeinstallerrc"
create_symlink "$HOME/dotfiles/systemsettingsrc" "$HOME/.config/systemsettingsrc"
create_symlink "$HOME/dotfiles/trashrc" "$HOME/.config/trashrc"
create_symlink "$HOME/dotfiles/Trolltech.conf" "$HOME/.config/Trolltech.conf"
create_symlink "$HOME/dotfiles/user-dirs.dirs" "$HOME/.config/user-dirs.dirs"
create_symlink "$HOME/dotfiles/user-dirs.locale" "$HOME/.config/user-dirs.locale"
create_symlink "$HOME/dotfiles/vlc" "$HOME/.config/vlc"
create_symlink "$HOME/dotfiles/xsettingsd" "$HOME/.config/xsettingsd"
